# Generated by Django 5.2.1 on 2025-10-18 23:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WagenUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tool', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'WAGen User',
                'verbose_name_plural': 'WAGen Users',
            },
        ),
        migrations.CreateModel(
            name='WagenProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('registration_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagen.wagenuser')),
            ],
            options={
                'verbose_name': 'WAGen Project',
                'verbose_name_plural': 'WAGen Projects',
            },
        ),
        migrations.CreateModel(
            name='WagenArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Area name')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wagen_area', to='wagen.wagenproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagen.wagenuser', verbose_name='User uploaded the area')),
            ],
            options={
                'verbose_name': 'WAGen Area',
                'verbose_name_plural': 'WAGen Areas',
                'db_table': 'wagen_area',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=150, verbose_name='Task id')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagen.wagenarea', verbose_name='Area where task run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagen.wagenuser', verbose_name='User running the task')),
            ],
            options={
                'verbose_name': 'Task History',
                'verbose_name_plural': 'Tasks History',
                'db_table': 'taskhistory',
                'ordering': ['-date'],
            },
        ),
    ]
