# Generated by Django 5.2.1 on 2025-10-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagenuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
