# Generated by Django 5.2.1 on 2025-10-17 19:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WIUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tool', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WIArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Area name')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='witool.wiuser', verbose_name='User uploaded the area')),
            ],
            options={
                'verbose_name': 'wagen_area',
                'verbose_name_plural': 'witool_areas',
                'db_table': 'witool_area',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=150, verbose_name='Task id')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='witool.wiarea', verbose_name='Area where task run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='witool.wiuser', verbose_name='User running the task')),
            ],
            options={
                'verbose_name': 'Task history',
                'verbose_name_plural': 'Tasks history',
                'db_table': 'reportsHistory',
                'ordering': ['-date'],
            },
        ),
    ]
