# Generated by Django 5.2.1 on 2025-10-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporthistory',
            options={'ordering': ['-date'], 'verbose_name': 'Report History', 'verbose_name_plural': 'Reports History'},
        ),
        migrations.AlterModelOptions(
            name='wiarea',
            options={'ordering': ['name'], 'verbose_name': 'WI Tools Area', 'verbose_name_plural': 'WI Tools Areas'},
        ),
        migrations.AlterModelOptions(
            name='wiuser',
            options={'verbose_name': 'WI Tools User', 'verbose_name_plural': 'WI Tools Users'},
        ),
        migrations.AddField(
            model_name='wiuser',
            name='username',
            field=models.CharField(default='temp_username', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wiuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
