# Generated by Django 5.2.1 on 2025-10-16 17:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WagenUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WagenProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('registration_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.wagenuser')),
            ],
            options={
                'unique_together': {('user', 'project_name')},
            },
        ),
        migrations.CreateModel(
            name='WagenArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Area name')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wagen_area', to='webapp.wagenproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.wagenuser', verbose_name='User uploaded the area')),
            ],
            options={
                'verbose_name': 'wagen_area',
                'verbose_name_plural': 'wagen_areas',
                'db_table': 'wagen_area',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=150, verbose_name='Task id')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.wagenarea', verbose_name='Area where task run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.wagenuser', verbose_name='User running the task')),
            ],
            options={
                'verbose_name': 'Task history',
                'verbose_name_plural': 'Tasks history',
                'db_table': 'taskhistory',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_thumbnail', models.JSONField(default=list)),
                ('registration_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.wagenuser')),
            ],
            options={
                'unique_together': {('user', 'project_name')},
            },
        ),
    ]
