# Generated by Django 5.2.1 on 2025-10-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wagenuser',
            name='otp',
        ),
    ]
